import { Plan } from './database.types';

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

function futureDate(daysFromNow: number) {
  return new Date(now + daysFromNow * day).toISOString();
}

export const demoPlans: Plan[] = [
  {
    id: 'demo_surf_playa_grande',
    creator_id: 'demo_people_conecta',
    nombre: 'Surf grupal y mates al atardecer',
    categoria: 'Deporte',
    descripcion: 'Encuentro para surfear olas juntos, nivel principiante/intermedio. Después nos quedamos con mates mirando caer el sol en Playa Grande.',
    zona: 'Playa Grande',
    fecha: futureDate(2),
    hora: '17:00',
    cupo_max: 6,
    cupo_actual: 2,
    foto_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=900',
    es_gratuito: true,
    precio: null,
    preferencia_genero: 'todos',
    estado: 'publicado',
    created_at: new Date().toISOString(),
    creator: {
      id: 'demo_people_conecta',
      nombre: 'People Conecta',
      foto_url: null,
      ciudad: 'Mar del Plata',
      zona: 'Centro',
      intereses: ['Deporte', 'Naturaleza'],
      plan_tier: 'free',
      aprobado: true,
      no_shows: 0,
      rating_promedio: 4.8,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'demo_cafe_idiomas',
    creator_id: 'demo_people_conecta',
    nombre: 'Intercambio de idiomas y café de especialidad',
    categoria: 'Idiomas',
    descripcion: 'Charla relajada en Güemes: una hora en inglés y otra en español para practicar sin presión y conocer gente nueva.',
    zona: 'Güemes',
    fecha: futureDate(4),
    hora: '18:30',
    cupo_max: 10,
    cupo_actual: 3,
    foto_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=900',
    es_gratuito: false,
    precio: 2500,
    preferencia_genero: 'todos',
    estado: 'publicado',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo_fogon_varese',
    creator_id: 'demo_people_conecta',
    nombre: 'Fogón acústico frente al mar',
    categoria: 'Música',
    descripcion: 'Traé instrumento, mate o algo para compartir. Rock nacional, canciones tranquis y ronda frente al mar cerca de Varese.',
    zona: 'Varese',
    fecha: futureDate(6),
    hora: '19:30',
    cupo_max: 12,
    cupo_actual: 3,
    foto_url: 'https://images.unsplash.com/photo-1532509156689-d9d151c890f6?auto=format&fit=crop&q=80&w=900',
    es_gratuito: true,
    precio: null,
    preferencia_genero: 'todos',
    estado: 'publicado',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo_juegos_centro',
    creator_id: 'demo_people_conecta',
    nombre: 'Noche de juegos de mesa modernos',
    categoria: 'Juegos',
    descripcion: 'Catan, Dixit, Carcassonne y juegos simples para romper el hielo. No hace falta experiencia previa.',
    zona: 'Centro',
    fecha: futureDate(8),
    hora: '20:30',
    cupo_max: 8,
    cupo_actual: 0,
    foto_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=900',
    es_gratuito: true,
    precio: null,
    preferencia_genero: 'todos',
    estado: 'publicado',
    created_at: new Date().toISOString(),
  },
];
